name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean dist folder
        run: |
          rm -rf dist

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
          gpg --list-secret-keys

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_PAT }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-outputs
          path: dist/
          retention-days: 5
